// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { AddRequestBuilder } from './add/addRequestBuilder';
import { IdRequestBuilder } from './id/idRequestBuilder';
import { IdAccountRequestBuilder } from './idAccount/idAccountRequestBuilder';
import { UpdateRequestBuilder } from './update/updateRequestBuilder';
import { BaseRequestBuilder, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /wordentity
 */
export class WordentityRequestBuilder extends BaseRequestBuilder {
    /**
     * The add property
     */
    public get add(): AddRequestBuilder {
        return new AddRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The id property
     */
    public get id(): IdRequestBuilder {
        return new IdRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The idAccount property
     */
    public get idAccount(): IdAccountRequestBuilder {
        return new IdAccountRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The update property
     */
    public get update(): UpdateRequestBuilder {
        return new UpdateRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * Instantiates a new WordentityRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/wordentity");
    };
}
// tslint:enable
// eslint-enable
