// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { AddRequestBuilder } from './add/addRequestBuilder';
import { AllRequestBuilder } from './all/allRequestBuilder';
import { IdRequestBuilder } from './id/idRequestBuilder';
import { UpdateRequestBuilder } from './update/updateRequestBuilder';
import { BaseRequestBuilder, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /role
 */
export class RoleRequestBuilder extends BaseRequestBuilder {
    /**
     * The add property
     */
    public get add(): AddRequestBuilder {
        return new AddRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The all property
     */
    public get all(): AllRequestBuilder {
        return new AllRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The id property
     */
    public get id(): IdRequestBuilder {
        return new IdRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The update property
     */
    public get update(): UpdateRequestBuilder {
        return new UpdateRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * Instantiates a new RoleRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/role");
    };
}
// tslint:enable
// eslint-enable
