/* tslint:disable */
/* eslint-disable */
/**
 * BuddyLanguage.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface AddUserRequest
 */
export interface AddUserRequest {

    /**
     * @type {string}
     * @memberof AddUserRequest
     */
    firstName: string;

    /**
     * @type {string}
     * @memberof AddUserRequest
     */
    lastName: string;

    /**
     * @type {string}
     * @memberof AddUserRequest
     */
    telegramId: string;
}
