// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AddRoleRequest extends Parsable {
    /**
     * The name property
     */
    name?: string;
    /**
     * The prompt property
     */
    prompt?: string;
}
export function createAddRoleRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoAddRoleRequest;
}
export function deserializeIntoAddRoleRequest(addRoleRequest: AddRoleRequest | undefined = {} as AddRoleRequest) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { addRoleRequest.name = n.getStringValue(); },
        "prompt": n => { addRoleRequest.prompt = n.getStringValue(); },
    }
}
export function serializeAddRoleRequest(writer: SerializationWriter, addRoleRequest: AddRoleRequest | undefined = {} as AddRoleRequest) : void {
        writer.writeStringValue("name", addRoleRequest.name);
        writer.writeStringValue("prompt", addRoleRequest.prompt);
}
// tslint:enable
// eslint-enable
