// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AddUserRequest extends Parsable {
    /**
     * The firstName property
     */
    firstName?: string;
    /**
     * The lastName property
     */
    lastName?: string;
    /**
     * The telegramId property
     */
    telegramId?: string;
}
export function createAddUserRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoAddUserRequest;
}
export function deserializeIntoAddUserRequest(addUserRequest: AddUserRequest | undefined = {} as AddUserRequest) : Record<string, (node: ParseNode) => void> {
    return {
        "firstName": n => { addUserRequest.firstName = n.getStringValue(); },
        "lastName": n => { addUserRequest.lastName = n.getStringValue(); },
        "telegramId": n => { addUserRequest.telegramId = n.getStringValue(); },
    }
}
export function serializeAddUserRequest(writer: SerializationWriter, addUserRequest: AddUserRequest | undefined = {} as AddUserRequest) : void {
        writer.writeStringValue("firstName", addUserRequest.firstName);
        writer.writeStringValue("lastName", addUserRequest.lastName);
        writer.writeStringValue("telegramId", addUserRequest.telegramId);
}
// tslint:enable
// eslint-enable
