/* tslint:disable */
/* eslint-disable */
/**
 * BuddyLanguage.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Language } from './language';
import { Role } from './role';
import { TtsSpeed } from './tts-speed';
import { Voice } from './voice';
// import {
//     Language,Role,TtsSpeed,Voice,
// } from ".";

/**
 * 
 *
 * @export
 * @interface Preferences
 */
export interface Preferences {

    /**
     * @type {Language}
     * @memberof Preferences
     */
    nativeLanguage?: Language;

    /**
     * @type {Language}
     * @memberof Preferences
     */
    targetLanguage?: Language;

    /**
     * @type {Voice}
     * @memberof Preferences
     */
    selectedVoice?: Voice;

    /**
     * @type {TtsSpeed}
     * @memberof Preferences
     */
    selectedSpeed?: TtsSpeed;

    /**
     * @type {string}
     * @memberof Preferences
     */
    assistantRoleId: string;

    /**
     * @type {Role}
     * @memberof Preferences
     */
    assistantRole?: Role;
}
