// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export function createPreferencesFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoPreferences;
}
export function deserializeIntoPreferences(preferences: Preferences | undefined = {} as Preferences) : Record<string, (node: ParseNode) => void> {
    return {
        "nativeLanguage": n => { preferences.nativeLanguage = n.getNumberValue(); },
        "selectedSpeed": n => { preferences.selectedSpeed = n.getNumberValue(); },
        "selectedVoice": n => { preferences.selectedVoice = n.getNumberValue(); },
        "targetLanguage": n => { preferences.targetLanguage = n.getNumberValue(); },
    }
}
export interface Preferences extends Parsable {
    /**
     * The nativeLanguage property
     */
    nativeLanguage?: number;
    /**
     * The selectedSpeed property
     */
    selectedSpeed?: number;
    /**
     * The selectedVoice property
     */
    selectedVoice?: number;
    /**
     * The targetLanguage property
     */
    targetLanguage?: number;
}
export function serializePreferences(writer: SerializationWriter, preferences: Preferences | undefined = {} as Preferences) : void {
        writer.writeNumberValue("nativeLanguage", preferences.nativeLanguage);
        writer.writeNumberValue("selectedSpeed", preferences.selectedSpeed);
        writer.writeNumberValue("selectedVoice", preferences.selectedVoice);
        writer.writeNumberValue("targetLanguage", preferences.targetLanguage);
}
// tslint:enable
// eslint-enable
