// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';
import { type Guid } from 'guid-typescript';

export function createRoleResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoRoleResponse;
}
export function deserializeIntoRoleResponse(roleResponse: RoleResponse | undefined = {} as RoleResponse) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { roleResponse.id = n.getGuidValue(); },
        "name": n => { roleResponse.name = n.getStringValue(); },
        "prompt": n => { roleResponse.prompt = n.getStringValue(); },
    }
}
export interface RoleResponse extends Parsable {
    /**
     * The id property
     */
    id?: Guid;
    /**
     * The name property
     */
    name?: string;
    /**
     * The prompt property
     */
    prompt?: string;
}
export function serializeRoleResponse(writer: SerializationWriter, roleResponse: RoleResponse | undefined = {} as RoleResponse) : void {
        writer.writeGuidValue("id", roleResponse.id);
        writer.writeStringValue("name", roleResponse.name);
        writer.writeStringValue("prompt", roleResponse.prompt);
}
// tslint:enable
// eslint-enable
