// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';
import { type Guid } from 'guid-typescript';

export function createRoleByIdRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoRoleByIdRequest;
}
export function deserializeIntoRoleByIdRequest(roleByIdRequest: RoleByIdRequest | undefined = {} as RoleByIdRequest) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { roleByIdRequest.id = n.getGuidValue(); },
    }
}
export interface RoleByIdRequest extends Parsable {
    /**
     * The id property
     */
    id?: Guid;
}
export function serializeRoleByIdRequest(writer: SerializationWriter, roleByIdRequest: RoleByIdRequest | undefined = {} as RoleByIdRequest) : void {
        writer.writeGuidValue("id", roleByIdRequest.id);
}
// tslint:enable
// eslint-enable
