/* tslint:disable */
/* eslint-disable */
/**
 * BuddyLanguage.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface RoleResponse
 */
export interface RoleResponse {

    /**
     * @type {string}
     * @memberof RoleResponse
     */
    id?: string;

    /**
     * @type {string}
     * @memberof RoleResponse
     */
    name?: string | null;

    /**
     * @type {string}
     * @memberof RoleResponse
     */
    prompt?: string | null;
}
