// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';
import { type Guid } from 'guid-typescript';

export function createRoleFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoRole;
}
export function deserializeIntoRole(role: Role | undefined = {} as Role) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { role.id = n.getGuidValue(); },
        "name": n => { role.name = n.getStringValue(); },
        "prompt": n => { role.prompt = n.getStringValue(); },
    }
}
export interface Role extends Parsable {
    /**
     * The id property
     */
    id?: Guid;
    /**
     * The name property
     */
    name?: string;
    /**
     * The prompt property
     */
    prompt?: string;
}
export function serializeRole(writer: SerializationWriter, role: Role | undefined = {} as Role) : void {
        writer.writeGuidValue("id", role.id);
        writer.writeStringValue("name", role.name);
        writer.writeStringValue("prompt", role.prompt);
}
// tslint:enable
// eslint-enable
