// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';
import { type Guid } from 'guid-typescript';

export function createUpdateRoleRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoUpdateRoleRequest;
}
export function deserializeIntoUpdateRoleRequest(updateRoleRequest: UpdateRoleRequest | undefined = {} as UpdateRoleRequest) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { updateRoleRequest.id = n.getGuidValue(); },
        "name": n => { updateRoleRequest.name = n.getStringValue(); },
        "prompt": n => { updateRoleRequest.prompt = n.getStringValue(); },
    }
}
export function serializeUpdateRoleRequest(writer: SerializationWriter, updateRoleRequest: UpdateRoleRequest | undefined = {} as UpdateRoleRequest) : void {
        writer.writeGuidValue("id", updateRoleRequest.id);
        writer.writeStringValue("name", updateRoleRequest.name);
        writer.writeStringValue("prompt", updateRoleRequest.prompt);
}
export interface UpdateRoleRequest extends Parsable {
    /**
     * The id property
     */
    id?: Guid;
    /**
     * The name property
     */
    name?: string;
    /**
     * The prompt property
     */
    prompt?: string;
}
// tslint:enable
// eslint-enable
