/* tslint:disable */
/* eslint-disable */
/**
 * BuddyLanguage.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { RoleType } from './role-type';

/**
 * 
 *
 * @export
 * @interface UpdateRoleRequest
 */
export interface UpdateRoleRequest {

    /**
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    id: string;

    /**
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    name: string;

    /**
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    prompt: string;

    /**
     * @type {RoleType}
     * @memberof UpdateRoleRequest
     */
    roleType: RoleType;
}
