// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';
import { type Guid } from 'guid-typescript';

export function createUpdateRoleResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoUpdateRoleResponse;
}
export function deserializeIntoUpdateRoleResponse(updateRoleResponse: UpdateRoleResponse | undefined = {} as UpdateRoleResponse) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { updateRoleResponse.id = n.getGuidValue(); },
        "name": n => { updateRoleResponse.name = n.getStringValue(); },
        "prompt": n => { updateRoleResponse.prompt = n.getStringValue(); },
    }
}
export function serializeUpdateRoleResponse(writer: SerializationWriter, updateRoleResponse: UpdateRoleResponse | undefined = {} as UpdateRoleResponse) : void {
        writer.writeGuidValue("id", updateRoleResponse.id);
        writer.writeStringValue("name", updateRoleResponse.name);
        writer.writeStringValue("prompt", updateRoleResponse.prompt);
}
export interface UpdateRoleResponse extends Parsable {
    /**
     * The id property
     */
    id?: Guid;
    /**
     * The name property
     */
    name?: string;
    /**
     * The prompt property
     */
    prompt?: string;
}
// tslint:enable
// eslint-enable
