// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';
import { type Guid } from 'guid-typescript';

export function createUserResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) {
    if(!parseNode) throw new Error("parseNode cannot be undefined");
    return deserializeIntoUserResponse;
}
export function deserializeIntoUserResponse(userResponse: UserResponse | undefined = {} as UserResponse) : Record<string, (node: ParseNode) => void> {
    return {
        "firstName": n => { userResponse.firstName = n.getStringValue(); },
        "id": n => { userResponse.id = n.getGuidValue(); },
        "lastName": n => { userResponse.lastName = n.getStringValue(); },
        "telegramId": n => { userResponse.telegramId = n.getStringValue(); },
    }
}
export function serializeUserResponse(writer: SerializationWriter, userResponse: UserResponse | undefined = {} as UserResponse) : void {
        writer.writeStringValue("firstName", userResponse.firstName);
        writer.writeGuidValue("id", userResponse.id);
        writer.writeStringValue("lastName", userResponse.lastName);
        writer.writeStringValue("telegramId", userResponse.telegramId);
}
export interface UserResponse extends Parsable {
    /**
     * The firstName property
     */
    firstName?: string;
    /**
     * The id property
     */
    id?: Guid;
    /**
     * The lastName property
     */
    lastName?: string;
    /**
     * The telegramId property
     */
    telegramId?: string;
}
// tslint:enable
// eslint-enable
