/* tslint:disable */
/* eslint-disable */
/**
 * BuddyLanguage.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {
    
} from ".";

/**
 * 
 *
 * @export
 * @interface UserResponse
 */
export interface UserResponse {

    /**
     * @type {string}
     * @memberof UserResponse
     */
    id?: string;

    /**
     * @type {string}
     * @memberof UserResponse
     */
    firstName?: string | null;

    /**
     * @type {string}
     * @memberof UserResponse
     */
    lastName?: string | null;

    /**
     * @type {string}
     * @memberof UserResponse
     */
    telegramId?: string | null;
}
