/* tslint:disable */
/* eslint-disable */
/**
 * BuddyLanguage.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// import { Language } from './language';
// import { WordEntityStatus } from './word-entity-status';
import {
    Language,WordEntityStatus,
} from ".";

/**
 * 
 *
 * @export
 * @interface WordEntityResponse
 */
export interface WordEntityResponse {

    /**
     * @type {string}
     * @memberof WordEntityResponse
     */
    id?: string;

    /**
     * @type {string}
     * @memberof WordEntityResponse
     */
    accountId?: string;

    /**
     * @type {string}
     * @memberof WordEntityResponse
     */
    word?: string | null;

    /**
     * @type {Language}
     * @memberof WordEntityResponse
     */
    language?: Language;

    /**
     * @type {WordEntityStatus}
     * @memberof WordEntityResponse
     */
    status?: WordEntityStatus;
}
