/* tslint:disable */
/* eslint-disable */
/**
 * BuddyLanguage.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

// import { Language } from './language';
// import { User } from './user';
// import { WordEntityStatus } from './word-entity-status';
import {
    Language,User,WordEntityStatus,
} from ".";

/**
 * 
 *
 * @export
 * @interface WordEntity
 */
export interface WordEntity {

    /**
     * @type {string}
     * @memberof WordEntity
     */
    id?: string;

    /**
     * @type {Language}
     * @memberof WordEntity
     */
    language?: Language;

    /**
     * @type {WordEntityStatus}
     * @memberof WordEntity
     */
    wordStatus?: WordEntityStatus;

    /**
     * @type {string}
     * @memberof WordEntity
     */
    userId?: string;

    /**
     * @type {User}
     * @memberof WordEntity
     */
    user?: User;

    /**
     * @type {string}
     * @memberof WordEntity
     */
    word?: string | null;
}
