// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { deserializeIntoRoleByIdRequest, serializeRoleByIdRequest, type RoleByIdRequest } from '../../models/roleByIdRequest';
import { createRoleResponseFromDiscriminatorValue, deserializeIntoRoleResponse, serializeRoleResponse, type RoleResponse } from '../../models/roleResponse';
import { BaseRequestBuilder, HttpMethod, RequestInformation, type Parsable, type ParsableFactory, type RequestAdapter, type RequestOption } from '@microsoft/kiota-abstractions';

export interface IdRequestBuilderGetRequestConfiguration {
    /**
     * Request headers
     */
    headers?: Record<string, string[]>;
    /**
     * Request options
     */
    options?: RequestOption[];
}
/**
 * Builds and executes requests for operations under /role/id
 */
export class IdRequestBuilder extends BaseRequestBuilder {
    /**
     * Instantiates a new IdRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/role/id");
    };
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of RoleResponse
     */
    public get(body: RoleByIdRequest, requestConfiguration?: IdRequestBuilderGetRequestConfiguration | undefined) : Promise<RoleResponse | undefined> {
        const requestInfo = this.toGetRequestInformation(
            body, requestConfiguration
        );
        return this.requestAdapter.sendAsync<RoleResponse>(requestInfo, createRoleResponseFromDiscriminatorValue, undefined);
    };
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
    public toGetRequestInformation(body: RoleByIdRequest, requestConfiguration?: IdRequestBuilderGetRequestConfiguration | undefined) : RequestInformation {
        if(!body) throw new Error("body cannot be undefined");
        const requestInfo = new RequestInformation();
        if (requestConfiguration) {
            requestInfo.addRequestHeaders(requestConfiguration.headers);
            requestInfo.addRequestOptions(requestConfiguration.options);
        }
        requestInfo.urlTemplate = this.urlTemplate;
        requestInfo.pathParameters = this.pathParameters;
        requestInfo.httpMethod = HttpMethod.GET;
        requestInfo.tryAddRequestHeaders("Accept", "application/json;q=1, text/plain;q=0");
        requestInfo.setContentFromParsable(this.requestAdapter, "application/json", body, serializeRoleByIdRequest);
        return requestInfo;
    };
    /**
     * Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
     * @param rawUrl The raw URL to use for the request builder.
     * @returns a idRequestBuilder
     */
    public withUrl(rawUrl: string) : IdRequestBuilder {
        if(!rawUrl) throw new Error("rawUrl cannot be undefined");
        return new IdRequestBuilder(rawUrl, this.requestAdapter);
    };
}
// tslint:enable
// eslint-enable
