import { styled } from '@mui/material/styles';

export const Property1Default = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    width: '100%',
    height: `734px`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
});

export const TopBar = styled('div')({
    backgroundColor: `rgba(0, 20, 52, 1)`,
    boxShadow: `0px 0px 6px rgba(0, 0, 0, 0.12)`,
    borderRadius: `0px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
    width: `360px`,
    left: `0px`,
    top: `0px`,
});

/*export const TopBar1 = styled('div') ({
    alignSelf: `stretch`,
    width: `360px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});*/

export const Content = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `12px 8px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});

export const IcLeft = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `24px`,
    height: `24px`,
    margin: `0px`,
});

export const Shape = styled('img')({
    height: `18px`,
    width: `10px`,
    position: `absolute`,
    left: `7px`,
    top: `3px`,
});

export const IconButtons = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px 0px 0px 8px`,
});

export const Icon7 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `16px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `24px`,
    textTransform: `none`,
    width: `24px`,
    margin: `0px`,
});

export const Title15 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `12px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `16px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const TabGroup = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    width: `360px`,
    left: `0px`,
    top: `104px`,
    overflow: `hidden`,
});
  
export const Tab = styled('div')({
    backgroundColor: `rgba(177, 188, 205, 1)`,
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `8px`,
    flex: `1`,
    margin: `0px`,
});
  
export const Title = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `12px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `16px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Tab1 = styled('div')({
    backgroundColor: `rgba(177, 188, 205, 1)`,
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `8px`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
});
  
export const Title1 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `12px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `16px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Tab2 = styled('div')({
    backgroundColor: `rgba(177, 188, 205, 1)`,
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `8px`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
});
  
export const Title2 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `12px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `16px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const SectionTitle = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `16px 12px 0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    width: `360px`,
    left: `0px`,
    top: `148px`,
});
  
export const Text = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px`,
});
  
export const Title3 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `18px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `24px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const List = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    width: `360px`,
    left: `0px`,
    top: `200px`,
    overflow: `hidden`,
});
  
export const Row = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Metric = styled('div')({
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `12px`,
    flex: `1`,
    margin: `0px`,
    overflow: `hidden`,
});
  
export const Title4 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(177, 188, 205, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Data = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `35px`,
    margin: `4px 0px 0px 0px`,
});
  
export const SectionTitle1 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `16px 12px 0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    width: `360px`,
    left: `0px`,
    top: `288px`,
});
  
export const Text1 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px`,
});
  
export const Title5 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `18px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `24px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const List1 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    width: `360px`,
    left: `0px`,
    top: `340px`,
    overflow: `hidden`,
});
  
export const Row1 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Metric1 = styled('div')({
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `12px`,
    flex: `1`,
    margin: `0px`,
    overflow: `hidden`,
});
  
export const Title6 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(177, 188, 205, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14.5px`,
    textTransform: `none`,
    width: `152px`,
    margin: `0px`,
});
  
export const Data1 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `35px`,
    margin: `4px 0px 0px 0px`,
});
  
export const Metric2 = styled('div')({
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `12px`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
    overflow: `hidden`,
});
  
export const Title7 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(177, 188, 205, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14.5px`,
    textTransform: `none`,
    width: `114px`,
    margin: `0px`,
});
  
export const Data2 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `35px`,
    margin: `4px 0px 0px 0px`,
});
  
export const List2 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    width: `360px`,
    left: `0px`,
    top: `448px`,
});
  
export const Item = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `12px 0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Frame = styled('div')({
    backgroundColor: `rgba(177, 188, 205, 1)`,
    borderRadius: `16px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `32px`,
    height: `32px`,
    margin: `0px`,
});
  
export const Icon1 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `32px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    width: `32px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
  
export const Frame427318906 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
});
  
export const Title8 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Subtitle = styled('div')({
    textAlign: `right`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14.5px`,
    textTransform: `none`,
    width: `124px`,
    margin: `0px 0px 0px 8px`,
});
  
export const Vector200 = styled('img')({
    height: `0px`,
    width: `336px`,
    position: `absolute`,
    left: `0px`,
    top: `56px`,
});
  
export const Item1 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `12px 0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Frame1 = styled('div')({
    backgroundColor: `rgba(177, 188, 205, 1)`,
    borderRadius: `16px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `32px`,
    height: `32px`,
    margin: `0px`,
});
  
export const Icon2 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `32px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    width: `32px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
  
export const Frame4273189061 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
});
  
export const Title9 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14.5px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Subtitle1 = styled('div')({
    textAlign: `right`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px 0px 0px 8px`,
});
  
export const Vector2001 = styled('img')({
    height: `0px`,
    width: `336px`,
    position: `absolute`,
    left: `0px`,
    top: `56px`,
});
  
export const Item2 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `12px 0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Frame2 = styled('div')({
    backgroundColor: `rgba(177, 188, 205, 1)`,
    borderRadius: `16px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `32px`,
    height: `32px`,
    margin: `0px`,
});
  
export const Icon3 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `32px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    width: `32px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
  
export const Frame4273189062 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
});
  
export const Title10 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    width: `203px`,
    margin: `0px`,
});
  
export const Subtitle2 = styled('div')({
    textAlign: `right`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px 0px 0px 8px`,
});
  
export const Vector2002 = styled('img')({
    height: `0px`,
    width: `336px`,
    position: `absolute`,
    left: `0px`,
    top: `56px`,
});
  
export const Item3 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `12px 0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Frame3 = styled('div')({
    backgroundColor: `rgba(177, 188, 205, 1)`,
    borderRadius: `16px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `32px`,
    height: `32px`,
    margin: `0px`,
});
  
export const Icon4 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `32px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    width: `32px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
  
export const Frame4273189063 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
});
  
export const Title11 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Subtitle3 = styled('div')({
    textAlign: `right`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px 0px 0px 8px`,
});
  
export const Vector2003 = styled('img')({
    height: `0px`,
    width: `336px`,
    position: `absolute`,
    left: `0px`,
    top: `56px`,
});
  
export const BottomNav = styled('div')({
    backgroundColor: `rgba(0, 20, 52, 1)`,
    boxShadow: `0px 0px 6px rgba(0, 0, 0, 0.12)`,
    borderRadius: `0px`,
    display: `flex`,
    position: `absolute`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    width: `360px`,
    left: `0px`,
    top: `684px`,
    overflow: `hidden`,
});
  
export const Tab3 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `4px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px`,
});
  
export const Icon5 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `28px`,
    margin: `0px`,
});
  
export const Title12 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(230, 252, 255, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `10px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const Tab4 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `7px 4px 4px 4px`,
    boxSizing: `border-box`,
    width: `122px`,
    height: `48px`,
    margin: `0px`,
});
  
export const FreeIconScrabble7880 = styled('img')({
    height: `23px`,
    width: `21px`,
    objectFit: `cover`,
    margin: `0px`,
});
  
export const Title13 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(230, 252, 255, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `10px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `2px 0px 0px 0px`,
});
  
export const Tab5 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `4px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px`,
});
  
export const Icon6 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `28px`,
    margin: `0px`
});
  
export const Title14 = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(230, 252, 255, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `10px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});