import { styled } from '@mui/material/styles';
import { Link } from "react-router-dom";

export const Property1Default = styled('div')({
    backgroundColor: `rgba(230, 252, 255, 1)`,
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    width: '100%',
    height: `740px`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px 0px 12px 0px`,
    boxSizing: `border-box`,
});

export const TopBar = styled('div')({
    backgroundColor: `rgba(0, 20, 52, 1)`,
    boxShadow: `0px 0px 6px rgba(0, 0, 0, 0.12)`,
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});

export const Content = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `12px 8px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});

export const TitleStatistics = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(230, 252, 255, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `24px`,
    textTransform: `none`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
});

export const IconBox = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `0px`,
    boxSizing: `border-box`,
    margin: `0px 0px 0px 8px`,
});

export const IconRobot = styled('img')({
    height: `44px`,
    width: `43px`,
    margin: `0px`,
});
  
export const SectionTitle = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `16px 12px 0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    width: `360px`,
    left: `0px`,
    margin: `20px 0px 0px 0px`,
});
  
export const Text = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px`,
});
  
export const TitleHeading = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `18px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `24px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const List1 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `12px 0px 0px 0px`,
    overflow: `hidden`,
    gap: `8px`,
});
  
export const GroupNumberOfMessages = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const NumberOfMessages = styled('div')({
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `12px`,
    flex: `1`,
    margin: `0px`,
    overflow: `hidden`,
});
  
export const Title1 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(177, 188, 205, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const OutputNumberOfMessages = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `35px`,
    margin: `4px 0px 0px 0px`,
});
  
export const List2 = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `12px 0px 0px 0px`,
    overflow: `hidden`,
});
  
export const GroupLanguage = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const NumberOfWordsStudied = styled('div')({
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `12px`,
    height: `95px`,
    flex: `1`,
    margin: `0px`,
    overflow: `hidden`,
});
  
export const Title2 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(177, 188, 205, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14.5px`,
    textTransform: `none`,
    width: `152px`,
    margin: `0px`,
});
  
export const OutputNumberOfWordsStudied = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `35px`,
    margin: `4px 0px 0px 0px`,
});
  
export const NumberOfLearningWords = styled('div')({
    border: `1px solid rgba(0, 20, 52, 1)`,
    boxSizing: `border-box`,
    borderRadius: `6px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `12px`,
    height: `95px`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
    overflow: `hidden`,
});
  
export const OutputNumberOfLearningWords = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `35px`,
    margin: `4px 0px 0px 0px`,
});
  
export const Group = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `0px 12px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `30px 0px 32px 0px`,
});
  
export const SectionLearnedWords = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `12px 0px`,
    boxSizing: `border-box`,
    height: `56px`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const BoxIcon = styled('div')({
    backgroundColor: `rgba(177, 188, 205, 1)`,
    borderRadius: `16px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    width: `32px`,
    height: `32px`,
    margin: `0px`,
});
  
export const Icon = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `32px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    width: `32px`,
    position: `absolute`,
    left: `0px`,
    top: `0px`,
});
  
export const Label = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px 0px 0px 8px`,
});
  
export const Title3 = styled('div')({
    textAlign: `left`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const LabelViewList = styled('div')({
    textAlign: `right`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14.5px`,
    textTransform: `none`,
    width: `124px`,
    margin: `0px 0px 0px 8px`,
});
  
export const SectionDurationOfMessages = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `12px 0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    height: `56px`,
    margin: `0px`,
});
  
export const OutputDurationOfMessages = styled('div')({
    textAlign: `right`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px 0px 0px 8px`,
});
  
export const SectionNumberConsecutiveCommunicationDays = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `12px 0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    height: `56px`,
    margin: `0px`,
});
  
export const OutputNumberConsecutiveCommunicationDays = styled('div')({
    textAlign: `right`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px 0px 0px 8px`,
});
  
export const SectionNumberDaysCommunication = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `12px 0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    height: `56px`,
    margin: `0px`,
});
  
export const OutputNumberDaysCommunication = styled('div')({
    textAlign: `right`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 20, 52, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `500`,
    fontSize: `14px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `20px`,
    textTransform: `none`,
    margin: `0px 0px 0px 8px`,
});
  
export const BottomNav = styled('div')({
    backgroundColor: `rgba(0, 20, 52, 1)`,
    boxShadow: `0px 0px 6px rgba(0, 0, 0, 0.12)`,
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `row`,
    justifyContent: `flex-start`,
    alignItems: `flex-start`,
    padding: `0px`,
    boxSizing: `border-box`,
    alignSelf: `stretch`,
    margin: `0px 0px 0px 0px`,
});
  
export const ButtonHome = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `7px 4px 4px 4px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px`,
});
  
export const IconNav = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(0, 0, 0, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `20px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `28px`,
    textTransform: `none`,
    width: `28px`,
    margin: `0px`,
});
  
export const TitleIcon = styled('div')({
    textAlign: `center`,
    whiteSpace: `pre-wrap`,
    fontSynthesis: `none`,
    color: `rgba(230, 252, 255, 1)`,
    fontStyle: `normal`,
    fontFamily: `Roboto`,
    fontWeight: `400`,
    fontSize: `10px`,
    letterSpacing: `0px`,
    textDecoration: `none`,
    lineHeight: `14px`,
    textTransform: `none`,
    alignSelf: `stretch`,
    margin: `0px`,
});
  
export const ButtonWordEditor = styled(Link)({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `flex-start`,
    alignItems: `center`,
    padding: `7px 4px 4px 4px`,
    boxSizing: `border-box`,
    width: `122px`,
    height: `48px`,
    margin: `0px`,
    textDecorationLine: `none`,
});
  
export const IconWordEditor = styled('img')({
    height: `23px`,
    width: `21px`,
    objectFit: `cover`,
    margin: `0px`,
});
  
export const ButtonSettings = styled('div')({
    borderRadius: `0px`,
    display: `flex`,
    position: `relative`,
    isolation: `isolate`,
    flexDirection: `column`,
    justifyContent: `center`,
    alignItems: `center`,
    padding: `4px`,
    boxSizing: `border-box`,
    flex: `1`,
    margin: `0px`,
});