// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { RoleRequestBuilder } from './role/roleRequestBuilder';
import { UserRequestBuilder } from './user/userRequestBuilder';
import { WordentityRequestBuilder } from './wordentity/wordentityRequestBuilder';
import { BaseRequestBuilder, 
        enableBackingStoreForSerializationWriterFactory, 
        ParseNodeFactoryRegistry, 
        registerDefaultDeserializer, 
        registerDefaultSerializer, 
        SerializationWriterFactoryRegistry, 
        type RequestAdapter } from '@microsoft/kiota-abstractions';
import { FormParseNodeFactory, FormSerializationWriterFactory } from '@microsoft/kiota-serialization-form';
import { JsonParseNodeFactory, JsonSerializationWriterFactory } from '@microsoft/kiota-serialization-json';
import { MultipartSerializationWriterFactory } from '@microsoft/kiota-serialization-multipart';
import { TextParseNodeFactory, TextSerializationWriterFactory } from '@microsoft/kiota-serialization-text';

/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export class WebApiClient extends BaseRequestBuilder {
    /**
     * The role property
     */
    public get role(): RoleRequestBuilder {
        return new RoleRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The user property
     */
    public get user(): UserRequestBuilder {
        return new UserRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The wordentity property
     */
    public get wordentity(): WordentityRequestBuilder {
        return new WordentityRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * Instantiates a new WebApiClient and sets the default values.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(requestAdapter: RequestAdapter) {
        super({}, requestAdapter, "{+baseurl}");
        registerDefaultSerializer(JsonSerializationWriterFactory);
        registerDefaultSerializer(TextSerializationWriterFactory);
        registerDefaultSerializer(FormSerializationWriterFactory);
        registerDefaultSerializer(MultipartSerializationWriterFactory);
        registerDefaultDeserializer(JsonParseNodeFactory);
        registerDefaultDeserializer(TextParseNodeFactory);
        registerDefaultDeserializer(FormParseNodeFactory);
    }
}
// tslint:enable
// eslint-enable
