// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { AddRequestBuilder } from './add/addRequestBuilder';
import { Get_by_telegram_idRequestBuilder } from './get_by_telegram_id/get_by_telegram_idRequestBuilder';
import { GetRequestBuilder } from './get/getRequestBuilder';
import { UpdateRequestBuilder } from './update/updateRequestBuilder';
import { BaseRequestBuilder, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /user
 */
export class UserRequestBuilder extends BaseRequestBuilder {
    /**
     * The add property
     */
    public get add(): AddRequestBuilder {
        return new AddRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The get_by_telegram_id property
     */
    public get get_by_telegram_id(): Get_by_telegram_idRequestBuilder {
        return new Get_by_telegram_idRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The getPath property
     */
    public get getPath(): GetRequestBuilder {
        return new GetRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The update property
     */
    public get update(): UpdateRequestBuilder {
        return new UpdateRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * Instantiates a new UserRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/user");
    };
}
// tslint:enable
// eslint-enable
